import 'package:flutter/material.dart';

enum SkillType {
  active,
  passive,
}

class ClassSkill {
  final String id;
  final String name;
  final int requiredLevel;
  final SkillType type;
  final String cost;
  final int numericCost;
  final int cooldownSeconds;
  final IconData icon;
  final String summary;
  final String description;
  final Color themeColor;

  const ClassSkill({
    required this.id,
    required this.name,
    required this.requiredLevel,
    required this.type,
    required this.cost,
    this.numericCost = 0,
    this.cooldownSeconds = 0,
    required this.icon,
    required this.summary,
    required this.description,
    required this.themeColor,
  });
}

class ClassSkillCatalog {
  static const Map<String, List<ClassSkill>> skillsByClass = {
    'Vagabond': [
      ClassSkill(
        id: 'vagabond_emergency_triage',
        name: 'Emergency Triage',
        requiredLevel: 1,
        type: SkillType.active,
        cost: '20 Grit',
        numericCost: 20,
        cooldownSeconds: 6,
        icon: Icons.healing,
        summary: 'Restore 25 HP immediately in hostile zones.',
        description: 'Binds open wounds with sterilized scrap cloth. Cleanses minor bleed effects and restores 25 HP.',
        themeColor: Color(0xFFF59E0B),
      ),
      ClassSkill(
        id: 'vagabond_scavengers_eye',
        name: "Scavenger's Eye",
        requiredLevel: 3,
        type: SkillType.passive,
        cost: 'Passive',
        icon: Icons.remove_red_eye,
        summary: '+15% Relic & Silver Prism drop rate.',
        description: 'Sharp intuition tuned to hidden caches and glittering loot scattered across the Abyss.',
        themeColor: Color(0xFFF59E0B),
      ),
      ClassSkill(
        id: 'vagabond_makeshift_shiv',
        name: 'Makeshift Shiv',
        requiredLevel: 6,
        type: SkillType.active,
        cost: '25 Grit',
        numericCost: 25,
        cooldownSeconds: 4,
        icon: Icons.colorize,
        summary: 'Deal 140% DMG piercing 30% enemy armor.',
        description: 'Drives an improvised serrated blade through weak points in the target’s natural plating.',
        themeColor: Color(0xFFF59E0B),
      ),
      ClassSkill(
        id: 'vagabond_adrenaline_surge',
        name: 'Adrenaline Surge',
        requiredLevel: 10,
        type: SkillType.passive,
        cost: 'Passive',
        icon: Icons.bolt,
        summary: 'Below 30% HP: Gain +20% Evasion and +15% ATK.',
        description: 'Cornered rats fight the hardest. Heightens reflexes and physical strikes when facing mortal peril.',
        themeColor: Color(0xFFF59E0B),
      ),
      ClassSkill(
        id: 'vagabond_improvised_trap',
        name: 'Improvised Trap',
        requiredLevel: 15,
        type: SkillType.active,
        cost: '40 Grit',
        numericCost: 40,
        cooldownSeconds: 10,
        icon: Icons.pest_control_rodent,
        summary: 'Stun the target enemy for 1 turn & deal 80 Bleed.',
        description: 'Rig quick tripwires loaded with explosive powders to interrupt lethal enemy casts and immobilize.',
        themeColor: Color(0xFFF59E0B),
      ),
      ClassSkill(
        id: 'vagabond_resolve',
        name: "Vagabond's Resolve",
        requiredLevel: 20,
        type: SkillType.passive,
        cost: 'Passive',
        icon: Icons.shield,
        summary: 'Once per run: cheat fatal damage and revive at 40% HP.',
        description: 'Defies death itself through unyielding tenacity. Triggers a flash of adrenaline that restores 40% HP and 50 Grit.',
        themeColor: Color(0xFFF59E0B),
      ),
    ],

    'Juggernaut': [
      ClassSkill(
        id: 'juggernaut_brutal_cleave',
        name: 'Brutal Cleave',
        requiredLevel: 1,
        type: SkillType.active,
        cost: '20 Fury',
        numericCost: 20,
        cooldownSeconds: 4,
        icon: Icons.content_cut,
        summary: 'Deal 130% physical DMG to front line targets.',
        description: 'Swings an overwhelming weapon arc that crushes bone and sunders basic armor barriers.',
        themeColor: Color(0xFFEF4444),
      ),
      ClassSkill(
        id: 'juggernaut_iron_bastion',
        name: 'Iron Bastion',
        requiredLevel: 3,
        type: SkillType.passive,
        cost: 'Passive',
        icon: Icons.shield,
        summary: '+15% Total Armor value & +5% Block Chance.',
        description: 'Hardened stance that deflects heavy kinetic impact and solidifies defensive poise.',
        themeColor: Color(0xFFEF4444),
      ),
      ClassSkill(
        id: 'juggernaut_war_cry',
        name: 'War Cry',
        requiredLevel: 6,
        type: SkillType.active,
        cost: '30 Fury',
        numericCost: 30,
        cooldownSeconds: 8,
        icon: Icons.record_voice_over,
        summary: 'Demoralize enemies, reducing their ATK by 20% for 3 turns.',
        description: 'A deafening roar resonating across the chamber that shakes enemy resolve and lowers offensive output.',
        themeColor: Color(0xFFEF4444),
      ),
      ClassSkill(
        id: 'juggernaut_unstoppable_wrath',
        name: 'Unstoppable Wrath',
        requiredLevel: 10,
        type: SkillType.passive,
        cost: 'Passive',
        icon: Icons.fireplace,
        summary: '+0.5% Critical DMG per current point of Fury.',
        description: 'The hotter the blood boils, the more devastating every critical strike lands on enemy flesh.',
        themeColor: Color(0xFFEF4444),
      ),
      ClassSkill(
        id: 'juggernaut_ground_slam',
        name: 'Ground Slam',
        requiredLevel: 15,
        type: SkillType.active,
        cost: '50 Fury',
        numericCost: 50,
        cooldownSeconds: 12,
        icon: Icons.fitness_center,
        summary: 'AoE shockwave dealing 180% DMG & shattering 30% Armor.',
        description: 'Slams weapon directly into the earth, creating tremor ripples that rupture enemy balance and defenses.',
        themeColor: Color(0xFFEF4444),
      ),
      ClassSkill(
        id: 'juggernaut_colossus_avatar',
        name: 'Colossus Avatar',
        requiredLevel: 20,
        type: SkillType.active,
        cost: '80 Fury',
        numericCost: 80,
        cooldownSeconds: 20,
        icon: Icons.security,
        summary: 'Become immune to crowd control & reduce all DMG by 40% (3 turns).',
        description: 'Channels titanic ancestral wrath. Converts the wanderer into an immovable juggernaut of pure iron.',
        themeColor: Color(0xFFEF4444),
      ),
    ],

    'Phantom': [
      ClassSkill(
        id: 'phantom_shadow_strike',
        name: 'Shadow Strike',
        requiredLevel: 1,
        type: SkillType.active,
        cost: '30 Energy',
        numericCost: 30,
        cooldownSeconds: 4,
        icon: Icons.flash_on,
        summary: 'Phase behind the enemy for 160% DMG.',
        description: 'Vanishes into thin air and strikes from the blind spot with lethal precision.',
        themeColor: Color(0xFFFACC15),
      ),
      ClassSkill(
        id: 'phantom_evasion',
        name: 'Phantom Evasion',
        requiredLevel: 3,
        type: SkillType.passive,
        cost: 'Passive',
        icon: Icons.air,
        summary: '+12% Base Dodge & Evasion chance.',
        description: 'Blur effect when moving that leaves afterimages, confounding enemy tracking.',
        themeColor: Color(0xFFFACC15),
      ),
      ClassSkill(
        id: 'phantom_neurotoxin',
        name: 'Neurotoxin Coating',
        requiredLevel: 6,
        type: SkillType.passive,
        cost: 'Passive',
        icon: Icons.science,
        summary: 'Attacks inflict stacking Poison (15 DMG/turn, max 5 stacks).',
        description: 'Weapons are coated in distilled venom that melts nervous systems and ignores armor.',
        themeColor: Color(0xFFFACC15),
      ),
      ClassSkill(
        id: 'phantom_smoke_screen',
        name: 'Smoke Screen',
        requiredLevel: 10,
        type: SkillType.active,
        cost: '40 Energy',
        numericCost: 40,
        cooldownSeconds: 8,
        icon: Icons.cloud,
        summary: 'Break targeting & guarantee 100% Critical on next hit.',
        description: 'Detonates an alchemical smoke bomb, confounding enemies and setting up a deadly assassination.',
        themeColor: Color(0xFFFACC15),
      ),
      ClassSkill(
        id: 'phantom_flurry_of_blades',
        name: 'Flurry of Blades',
        requiredLevel: 15,
        type: SkillType.active,
        cost: '50 Energy',
        numericCost: 50,
        cooldownSeconds: 10,
        icon: Icons.sports_martial_arts,
        summary: 'Unleash 4 lightning-fast strikes for 70% DMG each (280% total).',
        description: 'A blur of cutting edges executing multiple slashes in the span of a single heartbeat.',
        themeColor: Color(0xFFFACC15),
      ),
      ClassSkill(
        id: 'phantom_void_execution',
        name: 'Void Execution',
        requiredLevel: 20,
        type: SkillType.active,
        cost: '70 Energy',
        numericCost: 70,
        cooldownSeconds: 15,
        icon: Icons.dangerous,
        summary: 'Instantly execute enemies below 20% HP; deal 350% DMG otherwise.',
        description: 'Opens a micro-tear in the void directly inside the target’s chest cavity.',
        themeColor: Color(0xFFFACC15),
      ),
    ],

    'Weaver': [
      ClassSkill(
        id: 'weaver_arcane_missile',
        name: 'Arcane Missile',
        requiredLevel: 1,
        type: SkillType.active,
        cost: '15 MP',
        numericCost: 15,
        cooldownSeconds: 3,
        icon: Icons.auto_fix_high,
        summary: '100% accurate magic projectile dealing 130% INT DMG.',
        description: 'Conjures a homing dart of concentrated aether that seeks out enemy life signatures and cannot miss.',
        themeColor: Color(0xFF38BDF8),
      ),
      ClassSkill(
        id: 'weaver_void_barrier',
        name: 'Void Barrier',
        requiredLevel: 3,
        type: SkillType.passive,
        cost: 'Passive',
        icon: Icons.all_inclusive,
        summary: 'Absorbs 20% incoming damage using Mana instead of HP.',
        description: 'An ethereal ward surrounding the weaver that converts kinetic trauma into mana depletion.',
        themeColor: Color(0xFF38BDF8),
      ),
      ClassSkill(
        id: 'weaver_frost_nova',
        name: 'Frost Nova',
        requiredLevel: 6,
        type: SkillType.active,
        cost: '25 MP',
        numericCost: 25,
        cooldownSeconds: 6,
        icon: Icons.ac_unit,
        summary: 'Blast dealing Ice DMG and slowing enemy attack speed by 30%.',
        description: 'Expels a ring of biting cold that freezes enemy limbs and delays their turn actions.',
        themeColor: Color(0xFF38BDF8),
      ),
      ClassSkill(
        id: 'weaver_elemental_resonance',
        name: 'Elemental Resonance',
        requiredLevel: 10,
        type: SkillType.passive,
        cost: 'Passive',
        icon: Icons.flare,
        summary: '+20% Damage to all Fire, Ice, and Lightning spells.',
        description: 'Attunes the soul to primal Ley lines, dramatically magnifying all spell potency.',
        themeColor: Color(0xFF38BDF8),
      ),
      ClassSkill(
        id: 'weaver_chain_lightning',
        name: 'Chain Lightning',
        requiredLevel: 15,
        type: SkillType.active,
        cost: '40 MP',
        numericCost: 40,
        cooldownSeconds: 10,
        icon: Icons.electric_bolt,
        summary: 'High electric discharge that arcs across up to 3 enemies.',
        description: 'Channels atmospheric high-voltage arcs that jump between targets with deafening thunder.',
        themeColor: Color(0xFF38BDF8),
      ),
      ClassSkill(
        id: 'weaver_astral_cataclysm',
        name: 'Astral Cataclysm',
        requiredLevel: 20,
        type: SkillType.active,
        cost: '70 MP',
        numericCost: 70,
        cooldownSeconds: 18,
        icon: Icons.wb_twilight,
        summary: 'Cosmic beam tearing through all enemy defenses for 320% DMG.',
        description: 'Tears a fissure in reality, collapsing astral starlight onto the battlefield in a radiant burst.',
        themeColor: Color(0xFF38BDF8),
      ),
    ],

    'Warden': [
      ClassSkill(
        id: 'warden_feral_command',
        name: 'Feral Command',
        requiredLevel: 1,
        type: SkillType.active,
        cost: '20 Animus',
        numericCost: 20,
        cooldownSeconds: 4,
        icon: Icons.pets,
        summary: 'Order companion to savage target for 120% DMG.',
        description: 'Directs the faithful beast companion to lunge at the enemy throat with crushing jaws.',
        themeColor: Color(0xFF10B981),
      ),
      ClassSkill(
        id: 'warden_pack_synergy',
        name: 'Pack Synergy',
        requiredLevel: 3,
        type: SkillType.passive,
        cost: 'Passive',
        icon: Icons.group_work,
        summary: 'Companion strikes generate +5 Animus and leech 10% HP to player.',
        description: 'A biological resonance linking warden and companion, feeding mutual lifeforce through predation.',
        themeColor: Color(0xFF10B981),
      ),
      ClassSkill(
        id: 'warden_entangling_roots',
        name: 'Entangling Roots',
        requiredLevel: 6,
        type: SkillType.active,
        cost: '30 Animus',
        numericCost: 30,
        cooldownSeconds: 7,
        icon: Icons.grass,
        summary: 'Roots enemy in thorny brambles, dealing Nature DoT and immobilizing.',
        description: 'Awakens ancient subterranean creepers that grip enemy legs and pierce through armor.',
        themeColor: Color(0xFF10B981),
      ),
      ClassSkill(
        id: 'warden_wild_symbiosis',
        name: 'Wild Symbiosis',
        requiredLevel: 10,
        type: SkillType.passive,
        cost: 'Passive',
        icon: Icons.healing,
        summary: '25% of damage taken by the player is transferred to the companion.',
        description: 'The companion shields its master with stalwart devotion, absorbing a portion of all mortal wounds.',
        themeColor: Color(0xFF10B981),
      ),
      ClassSkill(
        id: 'warden_primal_roar',
        name: 'Primal Roar',
        requiredLevel: 15,
        type: SkillType.active,
        cost: '45 Animus',
        numericCost: 45,
        cooldownSeconds: 12,
        icon: Icons.surround_sound,
        summary: 'Increase player & companion Attack Speed by 35% for 4 turns.',
        description: 'An echo of ancient apex predators that stimulates adrenaline and primal bloodlust.',
        themeColor: Color(0xFF10B981),
      ),
      ClassSkill(
        id: 'warden_wrath_of_the_wild',
        name: 'Wrath of the Wild',
        requiredLevel: 20,
        type: SkillType.active,
        cost: '80 Animus',
        numericCost: 80,
        cooldownSeconds: 20,
        icon: Icons.cruelty_free,
        summary: 'Transform companion into an Apex Titan for 4 turns (+60% DMG & Cleave).',
        description: 'Awakens the slumbering primal titan gene within the beast, expanding its size and destructive power.',
        themeColor: Color(0xFF10B981),
      ),
    ],
  };

  static List<ClassSkill> getSkillsForClass(String className) {
    // Normalise class name
    final cleaned = className.trim();
    if (skillsByClass.containsKey(cleaned)) {
      return skillsByClass[cleaned]!;
    }
    // Default fallback to Vagabond
    return skillsByClass['Vagabond']!;
  }
}
